server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
      fetch-registry: true

spring:
  application:
    name: entregas
  datasource:
    url: jdbc:postgresql://postgres:5432/GestionEntregas
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: developer07
    password: admin

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
